spring:
    application:
        name: Backend
    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            ddl-auto: create
        show-sql: true
    cloud:
        aws:
            credentials:
                accessKey: ${S3_ACCESS_KEY_ID}
                secretKey: ${S3_SECRET_ACCESS_KEY}
            region:
                static: ${S3_REGION}
            s3:
                bucket: ${S3_BUCKET_NAME}
            stack:
                auto: false
    security:
        oauth2:
            client:
                registration:
                    naver:
                        client_name: naver
                        client_id: ${CLIENT_ID}
                        client_secret: ${CLIENT_SECRET}
                        redirect_uri: ${REDIRECT_URI}
                        authorization_grant_type: authorization_code
                        scope: name,email,gender,birthday,profile_image,mobile

                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

    jwt:
        secret: ${JWT_SECRET}

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        url: http://back.pathsnap.shop/swagger-ui/index.html
    api-docs:
        enabled: true
        path: /v3/api-docs