name: Build Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test  # 유닛 테스트 실행

      - name: Remove .env file
        run: rm .env
