name: CI/CD for Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Set up environment variables
      run: |
        echo "${{ secrets.ENV }}" >> .env

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKE_HUB_USERNAME }}
        password: ${{ secrets.DOCKE_HUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKE_HUB_USERNAME }}/${{ secrets.DOCKE_HUB_REPOSITORY }}:latest .

    # Remove the .env file for security after the Docker build
    - name: Remove .env file
      run: rm .env

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKE_HUB_USERNAME }}/${{ secrets.DOCKE_HUB_REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_INSTANCE_IPADDRESS }}
        username: ${{ secrets.EC2_SERVER_USER }}
        key: ${{ secrets.EC2_INSTANCE_PRIVATEKEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKE_HUB_USERNAME }}/${{ secrets.DOCKE_HUB_REPOSITORY }}:latest
          sudo docker stop ${{ secrets.DOCKE_HUB_REPOSITORY }} || true
          sudo docker rm ${{ secrets.DOCKE_HUB_REPOSITORY }} || true
          sudo docker run -d -p 8080:8080 --name ${{ secrets.DOCKE_HUB_REPOSITORY }} ${{ secrets.DOCKE_HUB_USERNAME }}/${{ secrets.DOCKE_HUB_REPOSITORY }}:latest
